# Generated by Django 2.2.10 on 2020-03-30 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yearUpApp', '0002_auto_20200330_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
