# Generated by Django 2.2.10 on 2020-03-09 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yearUpApp', '0003_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
