# Generated by Django 2.2.10 on 2020-03-30 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yearUpApp', '0005_auto_20200330_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_mentor',
            field=models.BooleanField(default=False),
        ),
    ]
