# Generated by Django 2.2.10 on 2020-03-14 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yearUpApp', '0005_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
