# Generated by Django 2.2.10 on 2020-03-30 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yearUpApp', '0006_profile_is_mentor'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_mentee',
            field=models.BooleanField(default=False),
        ),
    ]
