# Generated by Django 2.2.10 on 2020-04-03 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yearUpApp', '0007_profile_is_mentee'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('IS_MENTOR', 'MENTOR'), ('IS_MENTEE', 'MENTEE')], default='mentor', max_length=6),
        ),
    ]
