# Generated by Django 2.2.10 on 2020-04-03 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yearUpApp', '0008_profile_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('IS_MENTOR', 'MENTOR'), ('IS_MENTEE', 'MENTEE')], default='mentee', max_length=20),
        ),
    ]
