# Generated by Django 2.2.10 on 2020-04-03 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yearUpApp', '0009_auto_20200403_2328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_mentee',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_mentor',
        ),
    ]
