# Generated by Django 2.2.10 on 2020-04-03 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yearUpApp', '0012_auto_20200403_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='county',
            field=models.CharField(choices=[('SONOMA', 'Sonoma'), ('NAPA', 'Napa'), ('SOLANO', 'Solano'), ('CONTRACOSTA', 'Contra Costa'), ('ALAMEDA', 'Alameda'), ('SANTACLARA', 'Santa Clara'), ('SANMATEO', 'San Mateo'), ('SANFRAN', 'San Francisco'), ('MARIN', 'Marin')], default='', max_length=20),
        ),
    ]
