# Generated by Django 2.2.10 on 2020-04-04 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yearUpApp', '0013_profile_county'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='education',
            field=models.CharField(choices=[('HIGHSCHOOL', 'High School'), ('SOMECOLLEGE', 'Some College'), ('ASSOCIATES', 'Associates'), ('BACHELORS', 'Bachelors'), ('MASTERS', 'Masters'), ('DOCTORAL', 'Doctoral')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('HE', 'He/Him'), ('SHE', 'She/Her'), ('THEY', 'They/Them'), ('OTHER', 'Other')], default='', max_length=20),
        ),
    ]
