# Generated by Django 2.2.10 on 2020-04-04 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yearUpApp', '0014_auto_20200404_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='industry',
            field=models.CharField(choices=[('DATING', 'dating'), ('DIY', 'DIY'), ('ECOMERCE', 'e-commerce/delivery'), ('EDUCATION', 'education'), ('ENERGY', 'energy'), ('ENTERPRISE', 'enterprise'), ('FASHBEAU', 'fashion & beauty'), ('FINANCE', 'finance'), ('FOOD', 'food'), ('GAMING', 'gaming'), ('GOVTANDPOL', 'Government and Politics'), ('HEALTH', 'Health and Wellness'), ('INTERIORDESIGN', 'Interior Design'), ('MARKETING', 'Marketing'), ('MEDIA', 'Media and Entertainment'), ('MESSAGING', 'Messaging'), ('MUSIC', 'Music'), ('NONPROFIT', 'Nonprofit'), ('PAYMENT', 'Payment'), ('REALESTATE', 'Real Estate'), ('RETAIL', 'Retail'), ('SOCIALNET', 'Social Network'), ('SPORTS', 'Sports'), ('TECH', 'Technology'), ('TELECOM', 'Telecommunications'), ('TRANSPORTATION', 'Transportation'), ('TRAVEL', 'Travel'), ('VENCAP', 'Venture Capital'), ('WEARABLES', 'Wearables')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin_url',
            field=models.URLField(default=''),
        ),
    ]
