# Generated by Django 2.2.10 on 2020-04-04 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yearUpApp', '0016_remove_profile_linkedin_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
    ]
