# Generated by Django 2.2.10 on 2020-04-04 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yearUpApp', '0017_auto_20200404_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='funfact',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin',
            field=models.URLField(default='', max_length=20),
        ),
    ]
