# Generated by Django 2.2.10 on 2020-04-04 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yearUpApp', '0018_auto_20200404_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ethnicity',
            field=models.CharField(choices=[('CAUCASIAN', 'Caucasian'), ('LATINO', 'Hispanic or Latino'), ('BLACK', 'Black or African American'), ('NATIVE', 'Native American or American Indian'), ('OTHER', 'Other')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='learningtrack',
            field=models.CharField(choices=[('PROFDEV', 'Professional Development'), ('INTERVIEWSKILL', 'Interviewing Skills'), ('NETWORKING', 'Networking'), ('LEADERSHIP', 'Leadership'), ('PUBLICSPEAK', 'Public Speaking'), ('TECHSKILL', 'Technical Skills'), ('TIMEMANAGE', 'Time Management'), ('RESEARCH', 'Research'), ('TECHNOLOGY', 'Technology'), ('COMMUNICATION', 'Communication'), ('PM', 'Project Management'), ('UPDATES', 'Industry Updates')], default='', max_length=20),
        ),
    ]
