# Generated by Django 2.2.10 on 2020-06-05 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_endpoints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoint',
            name='owner',
            field=models.CharField(default='wit proj admin', max_length=128),
        ),
        migrations.AddField(
            model_name='mlalgorithm',
            name='description',
            field=models.CharField(default='ml endpoint description default', max_length=1000),
        ),
        migrations.AddField(
            model_name='mlalgorithm',
            name='owner',
            field=models.CharField(default='wit proj admin', max_length=128),
        ),
        migrations.AddField(
            model_name='mlalgorithm',
            name='version',
            field=models.CharField(default='1', max_length=128),
        ),
    ]
