# Generated by Django 2.2.10 on 2020-07-08 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_endpoints', '0002_auto_20200605_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlrequest',
            name='feedback',
            field=models.CharField(blank=True, max_length=10485760, null=True),
        ),
        migrations.AlterField(
            model_name='mlrequest',
            name='full_response',
            field=models.CharField(max_length=10485760),
        ),
        migrations.AlterField(
            model_name='mlrequest',
            name='input_data',
            field=models.CharField(max_length=10485760),
        ),
        migrations.AlterField(
            model_name='mlrequest',
            name='response',
            field=models.CharField(max_length=10485760),
        ),
    ]
