# Generated by Django 2.2.10 on 2020-04-04 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='company',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='county',
            field=models.CharField(choices=[('SONOMA', 'Sonoma'), ('NAPA', 'Napa'), ('SOLANO', 'Solano'), ('CONTRACOSTA', 'Contra Costa'), ('ALAMEDA', 'Alameda'), ('SANTACLARA', 'Santa Clara'), ('SANMATEO', 'San Mateo'), ('SANFRAN', 'San Francisco'), ('MARIN', 'Marin')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='education',
            field=models.CharField(choices=[('HIGHSCHOOL', 'High School'), ('SOMECOLLEGE', 'Some College'), ('ASSOCIATES', 'Associates'), ('BACHELORS', 'Bachelors'), ('MASTERS', 'Masters'), ('DOCTORAL', 'Doctoral')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='ethnicity',
            field=models.CharField(choices=[('CAUCASIAN', 'Caucasian'), ('LATINO', 'Hispanic or Latino'), ('BLACK', 'Black or African American'), ('NATIVE', 'Native American or American Indian'), ('OTHER', 'Other')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='funfact',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender_pronouns',
            field=models.CharField(choices=[('HE', 'He/Him'), ('SHE', 'She/Her'), ('THEY', 'They/Them'), ('OTHER', 'Other')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='industry',
            field=models.CharField(choices=[('DATING', 'dating'), ('DIY', 'DIY'), ('ECOMERCE', 'e-commerce/delivery'), ('EDUCATION', 'education'), ('ENERGY', 'energy'), ('ENTERPRISE', 'enterprise'), ('FASHBEAU', 'fashion & beauty'), ('FINANCE', 'finance'), ('FOOD', 'food'), ('GAMING', 'gaming'), ('GOVTANDPOL', 'Government and Politics'), ('HEALTH', 'Health and Wellness'), ('INTERIORDESIGN', 'Interior Design'), ('MARKETING', 'Marketing'), ('MEDIA', 'Media and Entertainment'), ('MESSAGING', 'Messaging'), ('MUSIC', 'Music'), ('NONPROFIT', 'Nonprofit'), ('PAYMENT', 'Payment'), ('REALESTATE', 'Real Estate'), ('RETAIL', 'Retail'), ('SOCIALNET', 'Social Network'), ('SPORTS', 'Sports'), ('TECH', 'Technology'), ('TELECOM', 'Telecommunications'), ('TRANSPORTATION', 'Transportation'), ('TRAVEL', 'Travel'), ('VENCAP', 'Venture Capital'), ('WEARABLES', 'Wearables')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='learningtrack',
            field=models.CharField(choices=[('PROFDEV', 'Professional Development'), ('INTERVIEWSKILL', 'Interviewing Skills'), ('NETWORKING', 'Networking'), ('LEADERSHIP', 'Leadership'), ('PUBLICSPEAK', 'Public Speaking'), ('TECHSKILL', 'Technical Skills'), ('TIMEMANAGE', 'Time Management'), ('RESEARCH', 'Research'), ('TECHNOLOGY', 'Technology'), ('COMMUNICATION', 'Communication'), ('PM', 'Project Management'), ('UPDATES', 'Industry Updates')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin',
            field=models.URLField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(default='YUBA', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, help_text='(000) 000-000', max_length=15),
        ),
        migrations.AddField(
            model_name='profile',
            name='job_title',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('IS_MENTOR', 'MENTOR'), ('IS_MENTEE', 'MENTEE')], default='mentee', max_length=20),
        ),
    ]
