# Generated by Django 2.2.10 on 2020-04-04 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0002_auto_20200404_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='county',
            field=models.CharField(choices=[('ALAMEDA', 'Alameda'), ('CONTRACOSTA', 'Contra Costa'), ('MARIN', 'Marin'), ('NAPA', 'Napa'), ('SANFRAN', 'San Francisco'), ('SANMATEO', 'San Mateo'), ('SANTACLARA', 'Santa Clara'), ('SOLANO', 'Solano'), ('SONOMA', 'Sonoma')], default='', max_length=20),
        ),
    ]
