# Generated by Django 2.2.10 on 2020-04-13 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0004_auto_20200404_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('IS_MENTOR', 'Mentor'), ('IS_MENTEE', 'Mentee')], default='mentee', max_length=20),
        ),
    ]
