# Generated by Django 2.2.10 on 2020-04-13 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0006_locationanswer_locationquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location_q',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='userProfile.LocationQuestion'),
        ),
    ]
