# Generated by Django 2.2.10 on 2020-04-13 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0007_profile_location_q'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
    ]
