# Generated by Django 2.2.10 on 2020-04-14 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0009_profile_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
    ]
