# Generated by Django 2.2.10 on 2020-04-14 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0010_remove_profile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(default='YUBA', max_length=50),
        ),
    ]
