# Generated by Django 2.2.10 on 2020-04-18 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0012_remove_profile_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='location_q',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='userProfile.LocationAnswer'),
        ),
    ]
