# Generated by Django 2.2.10 on 2020-04-19 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0014_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profileimage.png', null=True, upload_to=''),
        ),
    ]
