# Generated by Django 2.2.10 on 2020-04-20 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0017_auto_20200419_0418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='location_q',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='userProfile.LocationAnswer'),
            preserve_default=False,
        ),
    ]
