# Generated by Django 2.2.10 on 2020-04-21 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0018_auto_20200420_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='location_q',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userProfile.LocationAnswer'),
        ),
    ]
