# Generated by Django 2.2.10 on 2020-04-23 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0019_auto_20200421_0208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='location_q',
        ),
        migrations.DeleteModel(
            name='LocationAnswer',
        ),
        migrations.DeleteModel(
            name='LocationQuestion',
        ),
    ]
