# Generated by Django 2.2.10 on 2020-04-21 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0019_auto_20200421_0208'),
        ('userProfile', '0005_auto_20200421_2318'),
    ]

    operations = [
    ]
