# Generated by Django 2.2.10 on 2020-04-21 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0020_merge_20200421_2336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='location_q',
        ),
    ]
