# Generated by Django 2.2.10 on 2020-04-21 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0021_remove_profile_location_q'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LocationAnswer',
        ),
        migrations.DeleteModel(
            name='LocationQuestion',
        ),
    ]
