# Generated by Django 2.2.10 on 2020-04-23 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0021_auto_20200423_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='roll_out',
            field=models.BooleanField(default=False),
        ),
    ]
