# Generated by Django 2.2.10 on 2020-04-25 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0021_auto_20200425_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionalquestions',
            name='description',
        ),
        migrations.RemoveField(
            model_name='additionalquestions',
            name='roll_out',
        ),
    ]
