# Generated by Django 2.2.10 on 2020-04-25 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0022_auto_20200425_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userProfile.AdditionalQuestions'),
        ),
    ]
