# Generated by Django 2.2.10 on 2020-04-23 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0022_quiz_roll_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='name',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
