# Generated by Django 2.2.10 on 2020-04-25 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0023_response_form'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='user_responder',
            new_name='user',
        ),
    ]
