# Generated by Django 2.2.10 on 2020-04-24 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0023_quiz_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['created'], 'verbose_name_plural': 'Quizzes'},
        ),
    ]
