# Generated by Django 2.2.10 on 2020-04-24 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0023_quiz_name'),
        ('userProfile', '0005_auto_20200413_2246'),
    ]

    operations = [
    ]
