# Generated by Django 2.2.10 on 2020-04-25 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0024_auto_20200425_2059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='form',
            new_name='question_form',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='form',
            new_name='question_form',
        ),
        migrations.RenameField(
            model_name='response',
            old_name='form',
            new_name='question_form',
        ),
        migrations.AlterField(
            model_name='response',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userProfile.Profile'),
        ),
    ]
