# Generated by Django 2.2.10 on 2020-04-25 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0024_auto_20200425_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='location_q',
        ),
    ]
