# Generated by Django 2.2.10 on 2020-04-25 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0025_remove_profile_location_q'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LocationAnswer',
        ),
        migrations.DeleteModel(
            name='LocationQuestion',
        ),
    ]
