# Generated by Django 2.2.10 on 2020-04-25 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0025_remove_profile_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userProfile.Quiz'),
        ),
    ]
