# Generated by Django 2.2.10 on 2020-04-28 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0005_auto_20200417_2001'),
        ('userProfile', '0026_auto_20200425_2104'),
    ]

    operations = [
    ]
