# Generated by Django 2.2.10 on 2020-04-25 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0026_profile_quiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='quiz',
        ),
    ]
