# Generated by Django 2.2.10 on 2020-04-28 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0027_merge_20200428_1623'),
        ('userProfile', '0027_auto_20200428_2144'),
    ]

    operations = [
    ]
