# Generated by Django 2.2.10 on 2020-04-25 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0027_remove_profile_quiz'),
        ('userProfile', '0024_auto_20200424_2040'),
    ]

    operations = [
    ]
