# Generated by Django 2.2.10 on 2020-05-02 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0027_merge_20200428_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faq', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
