# Generated by Django 2.2.10 on 2020-05-02 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0028_faq'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FAQ',
        ),
    ]
