# Generated by Django 2.2.10 on 2020-05-03 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0029_delete_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrequentlyAsked',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(default='', max_length=5000)),
                ('question', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
