# Generated by Django 2.2.10 on 2020-04-30 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0029_auto_20200429_0018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_form',
        ),
        migrations.RemoveField(
            model_name='response',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='response',
            name='question',
        ),
        migrations.RemoveField(
            model_name='response',
            name='question_form',
        ),
        migrations.RemoveField(
            model_name='response',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='question_form',
        ),
        migrations.DeleteModel(
            name='AdditionalQuestions',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Response',
        ),
    ]
