# Generated by Django 2.2.10 on 2020-05-03 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0030_frequentlyasked'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frequentlyasked',
            options={'verbose_name_plural': 'Frequently Asked Questions'},
        ),
    ]
