# Generated by Django 2.2.10 on 2020-05-04 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0032_auto_20200504_1817'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FrequentlyAskedMentor',
            new_name='FrequentlyAsked',
        ),
    ]
