# Generated by Django 2.2.10 on 2020-05-09 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0035_auto_20200504_1824'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frequentlyasked',
            options={'verbose_name_plural': 'Frequently Asked Questions - Mentor'},
        ),
        migrations.RemoveField(
            model_name='frequentlyasked',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='frequentlyasked',
            name='question',
        ),
        migrations.AddField(
            model_name='frequentlyasked',
            name='mentor_answer',
            field=models.TextField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='frequentlyasked',
            name='mentor_question',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
