# Generated by Django 2.2.10 on 2020-05-09 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0036_auto_20200509_1817'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frequentlyasked',
            options={'verbose_name_plural': 'Frequently Asked Questions'},
        ),
        migrations.RenameField(
            model_name='frequentlyasked',
            old_name='mentor_answer',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='frequentlyasked',
            old_name='mentor_question',
            new_name='question',
        ),
    ]
