# Generated by Django 2.2.10 on 2020-05-09 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0037_auto_20200509_1818'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FrequentlyAsked',
            new_name='FrequentlyAskedQ',
        ),
    ]
