# Generated by Django 2.2.10 on 2020-05-09 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0039_auto_20200509_1824'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrequentlyAskedMentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentor_questions', models.CharField(default='', max_length=1000)),
                ('mentor_answers', models.TextField(default='', max_length=5000)),
            ],
            options={
                'verbose_name_plural': 'Frequently Asked Questions Mentor',
            },
        ),
    ]
