# Generated by Django 2.2.10 on 2020-05-19 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0040_frequentlyaskedmentor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frequentlyasked',
            options={'verbose_name_plural': 'Frequently Asked Questions Mentee'},
        ),
    ]
