# Generated by Django 2.2.10 on 2020-05-26 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0041_auto_20200519_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cohort',
            field=models.CharField(choices=[('SPRING20', 'Spring 2020'), ('FALL20', 'Fall 2020'), ('SPRING21', 'Spring 2021'), ('FALL21', 'Fall 2021')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='site_location',
            field=models.CharField(choices=[('YUBA', 'Bay Area')], default='', max_length=20),
        ),
    ]
