# Generated by Django 2.2.10 on 2020-05-26 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0041_auto_20200519_2150'),
        ('userProfile', '0031_auto_20200430_2357'),
    ]

    operations = [
    ]
