# Generated by Django 2.2.10 on 2020-05-26 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0042_auto_20200526_2335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='title',
            new_name='job_title',
        ),
    ]
