# Generated by Django 2.2.10 on 2020-05-26 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0043_auto_20200526_2338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='gender',
            new_name='gender_pronouns',
        ),
    ]
