# Generated by Django 2.2.10 on 2020-05-29 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0044_auto_20200526_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='learningtrack',
            field=models.CharField(choices=[('PM', 'Project Management'), ('IT', 'IT Helpdesk'), ('NS', 'Network/Desktop Support'), ('QA', 'Quality Assurance'), ('CYBER', 'Cyber Security'), ('DA', 'Data Analytics')], default='', max_length=20),
        ),
    ]
