# Generated by Django 2.2.10 on 2020-05-29 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0042_merge_20200526_1805'),
        ('userProfile', '0044_auto_20200526_2340'),
    ]

    operations = [
    ]
