# Generated by Django 2.2.10 on 2020-05-28 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0045_emailadmin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmailAdmin',
            new_name='Email',
        ),
    ]
