# Generated by Django 2.2.10 on 2020-06-04 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0045_merge_20200529_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='userProfile.Question'),
        ),
        migrations.AlterField(
            model_name='response',
            name='answer',
            field=models.ForeignKey(limit_choices_to=models.Q(question_id=1), null=True, on_delete=django.db.models.deletion.CASCADE, to='userProfile.Answer'),
        ),
    ]
