# Generated by Django 2.2.10 on 2020-05-29 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0046_auto_20200528_1545'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Email',
        ),
    ]
