# Generated by Django 2.2.10 on 2020-05-30 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0048_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='email_mentees',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='email',
            name='email_mentors',
            field=models.BooleanField(default=False),
        ),
    ]
