# Generated by Django 2.2.10 on 2020-05-30 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0049_auto_20200530_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='bcc_email_mentees',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='email',
            name='bcc_email_mentors',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='email',
            name='bcc_to_email',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='email',
            name='cc_email_mentees',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='email',
            name='cc_email_mentors',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='email',
            name='cc_to_email',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
