# Generated by Django 2.2.10 on 2020-05-31 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0052_auto_20200531_0124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='email',
            options={},
        ),
    ]
