# Generated by Django 2.2.10 on 2020-05-31 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0054_auto_20200531_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='email_mentees',
            field=models.BooleanField(default=False, verbose_name='Email All Mentees'),
        ),
    ]
