# Generated by Django 2.2.10 on 2020-05-31 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0055_auto_20200531_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='cc_to_email',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='CC:'),
        ),
    ]
