# Generated by Django 2.2.10 on 2020-05-31 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0057_auto_20200531_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='bcc_to_email',
            field=models.CharField(blank=True, default='', max_length=20000, verbose_name='BCC:'),
        ),
        migrations.AlterField(
            model_name='email',
            name='cc_to_email',
            field=models.CharField(blank=True, default='', max_length=20000, verbose_name='CC:'),
        ),
        migrations.AlterField(
            model_name='email',
            name='message_email',
            field=models.TextField(default='', max_length=30000),
        ),
        migrations.AlterField(
            model_name='email',
            name='subject',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='email',
            name='to_email',
            field=models.CharField(blank=True, default='', max_length=20000),
        ),
    ]
