# Generated by Django 2.2.10 on 2020-06-06 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0058_auto_20200531_2142'),
        ('userProfile', '0045_auto_20200529_1552'),
    ]

    operations = [
    ]
