# Generated by Django 2.2.10 on 2020-06-10 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0059_merge_20200606_0036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userProfile.Answer')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userProfile.Question')),
                ('question_form', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userProfile.AdditionalQuestions')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userProfile.Profile')),
            ],
        ),
    ]
