# Generated by Django 2.2.10 on 2020-06-11 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0046_auto_20200604_0020'),
        ('userProfile', '0059_merge_20200606_0036'),
    ]

    operations = [
    ]
