# Generated by Django 2.2.10 on 2020-06-07 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0059_merge_20200606_0036'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyPost',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('userProfile.profile',),
        ),
    ]
