# Generated by Django 2.2.10 on 2020-06-13 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0060_questionss'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Questionss',
        ),
    ]
