# Generated by Django 2.2.10 on 2020-06-13 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0061_delete_questionss'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalquestions',
            name='description',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AddField(
            model_name='additionalquestions',
            name='questions_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='additionalquestions',
            name='roll_out',
            field=models.BooleanField(default=False),
        ),
    ]
