# Generated by Django 2.2.10 on 2020-06-16 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0061_delete_mypost'),
        ('userProfile', '0060_merge_20200611_1944'),
    ]

    operations = [
    ]
