# Generated by Django 2.2.10 on 2020-06-13 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0062_auto_20200613_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionalquestions',
            name='description',
        ),
        migrations.RemoveField(
            model_name='additionalquestions',
            name='questions_count',
        ),
        migrations.RemoveField(
            model_name='additionalquestions',
            name='roll_out',
        ),
    ]
