# Generated by Django 2.2.10 on 2020-06-17 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0062_merge_20200616_2259'),
        ('userProfile', '0063_auto_20200616_1438'),
    ]

    operations = [
    ]
