# Generated by Django 2.2.10 on 2020-06-16 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0063_auto_20200616_1438'),
        ('userProfile', '0063_auto_20200616_2338'),
    ]

    operations = [
    ]
