# Generated by Django 2.2.10 on 2020-06-13 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0063_auto_20200613_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalquestions',
            name='questions_count',
            field=models.IntegerField(default=0),
        ),
    ]
