# Generated by Django 2.2.10 on 2020-06-13 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0064_additionalquestions_questions_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='answer',
        ),
    ]
