# Generated by Django 2.2.10 on 2020-06-18 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0064_merge_20200617_1327'),
        ('userProfile', '0062_merge_20200616_2354'),
    ]

    operations = [
    ]
