# Generated by Django 2.2.10 on 2020-06-27 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0065_merge_20200618_2200'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomNotifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=1000)),
                ('notify_mentors', models.BooleanField(default=False, verbose_name='Notify All Mentors')),
                ('notify_mentees', models.BooleanField(default=False, verbose_name='Notify All Mentees')),
                ('message', models.TextField(default='', max_length=5000)),
            ],
        ),
    ]
