# Generated by Django 2.2.10 on 2020-06-18 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0065_merge_20200617_2243'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='userProfile.Profile')),
            ],
        ),
    ]
