# Generated by Django 2.2.10 on 2020-06-23 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0066_matchprofile'),
        ('userProfile', '0065_merge_20200618_2200'),
    ]

    operations = [
    ]
