# Generated by Django 2.2.10 on 2020-06-13 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0066_response_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionalquestions',
            name='questions_count',
        ),
    ]
