# Generated by Django 2.2.10 on 2020-07-15 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0066_customnotifications'),
        ('userProfile', '0067_merge_20200623_2317'),
    ]

    operations = [
    ]
