# Generated by Django 2.2.10 on 2020-06-13 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0067_remove_additionalquestions_questions_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalquestions',
            name='questions_count',
            field=models.IntegerField(default=0),
        ),
    ]
