# Generated by Django 2.2.10 on 2020-04-24 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0012_auto_20200423_1503'),
        ('survey', '0012_auto_20200419_1516'),
    ]

    operations = [
    ]
