# Generated by Django 2.2.10 on 2020-04-21 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0012_auto_20200421_2318'),
        ('survey', '0012_auto_20200419_1516'),
    ]

    operations = [
    ]
