# Generated by Django 2.2.10 on 2020-04-28 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0013_merge_20200424_2302'),
        ('survey', '0020_auto_20200420_1742'),
    ]

    operations = [
    ]
