# Generated by Django 2.2.10 on 2020-04-29 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0024_auto_20200428_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('text', 'Big Text Box(multiple line)'), ('short-text', 'Small Text Box(one line)'), ('radio', 'Radio (Bubbles)'), ('select', 'Select One'), ('select-multiple', 'CheckBox (Select Multiple)'), ('select_image', 'Select Image'), ('integer', 'Number'), ('float', 'float'), ('date', 'Date')], default='text', max_length=200, verbose_name='Type'),
        ),
    ]
