# Generated by Django 2.2.10 on 2020-06-04 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=1000)),
                ('match_id', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Response_json',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_json', models.TextField()),
            ],
        ),
    ]
