# Generated by Django 2.2.10 on 2020-06-11 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0060_merge_20200611_1944'),
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='puser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userProfile.Profile', verbose_name='User'),
        ),
    ]
