# Generated by Django 2.2.10 on 2020-06-17 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0065_merge_20200617_2243'),
        ('match', '0003_remove_matches_puser'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='match_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userProfile.Profile'),
        ),
    ]
