# Generated by Django 2.2.10 on 2020-06-18 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0004_matches_match_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matches',
            name='match_profile',
        ),
    ]
