# Generated by Django 2.2.10 on 2020-06-18 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0065_merge_20200617_2243'),
        ('match', '0005_remove_matches_match_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='match_profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='userProfile.Profile'),
        ),
    ]
