# Generated by Django 2.2.10 on 2020-06-18 00:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('match', '0006_auto_20200618_0010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matches',
            name='match_users',
        ),
        migrations.AddField(
            model_name='matches',
            name='match_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='matches',
            name='puser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='getting_matched', to=settings.AUTH_USER_MODEL),
        ),
    ]
