# Generated by Django 2.2.10 on 2020-06-18 23:24

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0066_matchprofile'),
        ('match', '0007_auto_20200618_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='match_profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='userProfile.Profile'),
        ),
        migrations.AddField(
            model_name='matches',
            name='temp_id',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['match_profile__user_id']),
        ),
    ]
