# Generated by Django 2.2.10 on 2020-06-18 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0008_auto_20200618_2324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matches',
            name='temp_id',
        ),
    ]
