# Generated by Django 2.2.10 on 2020-06-18 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0009_remove_matches_temp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='user_id',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
