# Generated by Django 2.2.10 on 2020-06-19 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0066_matchprofile'),
        ('match', '0010_auto_20200618_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='user_profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to='userProfile.Profile'),
        ),
        migrations.AlterField(
            model_name='matches',
            name='match_profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_profile', to='userProfile.Profile'),
        ),
    ]
