# Generated by Django 2.2.10 on 2020-06-19 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0011_auto_20200619_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='match_id',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
