# Generated by Django 2.2.10 on 2020-06-21 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0066_matchprofile'),
        ('match', '0012_auto_20200619_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='profile_search',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userProfile.Profile'),
        ),
    ]
