# Generated by Django 2.2.10 on 2020-06-21 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0013_matches_profile_search'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matches',
            options={'verbose_name_plural': 'Matches'},
        ),
        migrations.AlterField(
            model_name='matches',
            name='match_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_profile', to='userProfile.Profile'),
        ),
        migrations.AlterField(
            model_name='matches',
            name='user_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to='userProfile.Profile'),
        ),
    ]
