# Generated by Django 2.2.10 on 2020-06-21 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0014_auto_20200621_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='match_profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_profile', to='userProfile.Profile'),
        ),
        migrations.AlterField(
            model_name='matches',
            name='user_profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to='userProfile.Profile'),
        ),
    ]
